# Generated by Django 5.0.1 on 2024-01-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now=True, verbose_name='Data de Criação'),
        ),
    ]
